#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    background = "#0077c2"
    foreground = "#ffffff"
    leading_diamond = "\u256d\u2500\ue0b6"
    style = "diamond"
    template = "\uf120 {{ .Name }} "
    type = "shell"

  [[blocks.segments]]
    background = "#ef5350"
    foreground = "#FFFB38"
    style = "diamond"
    template = "<parentBackground>\ue0b0</> \uf292 "
    type = "root"

  [[blocks.segments]]
    background = "#FF9248"
    foreground = "#2d3436"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \uf07b\uea9c{{ .Path }} "
    type = "path"
    [blocks.segments.properties]
      folder_icon = " \uf07b "
      home_icon = "\ue617"
      style = "folder"

  [[blocks.segments]]
    background = "#FFFB38"
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}", "{{ if gt .Ahead 0 }}#C792EA{{ end }}", "{{ if gt .Behind 0 }}#C792EA{{ end }}"]
    foreground = "#011627"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} "
    type = "git"
    [blocks.segments.properties]
      branch_icon = "\ue725 "
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    background = "#83769c"
    foreground = "#ffffff"
    style = "diamond"
    template = " \ueba2{{ .FormattedMs }}\u2800"
    trailing_diamond = "\ue0b4"
    type = "executiontime"
    [blocks.segments.properties]
      style = "roundrock"
      threshold = 0.0

[[blocks]]
  alignment = "right"
  type = "prompt"

  [[blocks.segments]]
    background = "#303030"
    foreground = "#3C873A"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
    trailing_diamond = "\ue0b4 "
    type = "node"
    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = " <#cc3a3a>\ue5fa</> "
      yarn_icon = " <#348cba>\ue6a7</>"

  [[blocks.segments]]
    background = "#306998"
    foreground = "#FFE873"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "python"

  [[blocks.segments]]
    background = "#0e8ac8"
    foreground = "#ffffff"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "java"

  [[blocks.segments]]
    background = "#0e0e0e"
    foreground = "#0d6da8"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue77f {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "dotnet"

  [[blocks.segments]]
    background = "#ffffff"
    foreground = "#06aad5"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "go"

  [[blocks.segments]]
    background = "#f3f0ec"
    foreground = "#925837"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "rust"

  [[blocks.segments]]
    background = "#e1e8e9"
    foreground = "#055b9c"
    leading_diamond = " \ue0b6"
    style = "diamond"
    template = "\ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "dart"

  [[blocks.segments]]
    background = "#ffffff"
    foreground = "#ce092f"
    leading_diamond = " \ue0b6"
    style = "diamond"
    template = "\ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "angular"

  [[blocks.segments]]
    background = "#1e293b"
    foreground = "#ffffff"
    leading_diamond = " \ue0b6"
    style = "diamond"
    template = "{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "nx"

  [[blocks.segments]]
    background = "#945bb3"
    foreground = "#359a25"
    leading_diamond = " \ue0b6"
    style = "diamond"
    template = "<#ca3c34>\ue624</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "julia"

  [[blocks.segments]]
    background = "#ffffff"
    foreground = "#9c1006"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "ruby"

  [[blocks.segments]]
    background = "#ffffff"
    foreground = "#5398c2"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\uf104<#f5bf45>\uf0e7</>\uf105 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4 "
    type = "azfunc"

  [[blocks.segments]]
    background = "#565656"
    foreground = "#faa029"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\ue7ad {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
    trailing_diamond = "\ue0b4 "
    type = "aws"

  [[blocks.segments]]
    background = "#316ce4"
    foreground = "#ffffff"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = "\uf308 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
    trailing_diamond = "\ue0b4"
    type = "kubectl"

  [[blocks.segments]]
    background = "#b2bec3"
    foreground = "#222222"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}}<#222222> \ue0b2</>"
    type = "os"
    [blocks.segments.properties]
      linux = "\ue712"
      macos = "\ue711"
      windows = "\ue70f"

  [[blocks.segments]]
    background = "#f36943"
    background_templates = ["{{if eq \"Charging\" .State.String}}#b8e994{{end}}", "{{if eq \"Discharging\" .State.String}}#fff34e{{end}}", "{{if eq \"Full\" .State.String}}#33DD2D{{end}}"]
    foreground = "#262626"
    invert_powerline = true
    leading_diamond = "\ue0b2"
    style = "diamond"
    template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 <#262626>\ue0b2</>"
    type = "battery"
    [blocks.segments.properties]
      charged_icon = "\uf240 "
      charging_icon = "\uf1e6 "
      discharging_icon = "\ue234 "

  [[blocks.segments]]
    background = "#40c4ff"
    foreground = "#ffffff"
    invert_powerline = true
    leading_diamond = "\ue0b2"
    style = "diamond"
    template = " \uf073 {{ .CurrentDate | date .Format }} "
    trailing_diamond = "\ue0b4"
    type = "time"
    [blocks.segments.properties]
      time_format = "Jan-02-06 3:04:05 PM"

[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"

  [[blocks.segments]]
    foreground = "#21c7c7"
    style = "plain"
    template = "\u2570\u2500"
    type = "text"

  [[blocks.segments]]
    foreground = "#e0f8ff"
    foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
    style = "plain"
    template = "\ue285\ueab6 "
    type = "status"
    [blocks.segments.properties]
      always_enabled = true

